version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8443:8443"
    volumes:
      - ./src:/code/src
      - ./.env:/code/.env
    command: [ "/bin/bash", "/code/start.sh" ]

    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-supportdb}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
